name: Test
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: $
          cache: 'npm'
      - name: Install npm and angular packages
        run: |
          cd frontend/angular/crypto
          npm ci
  build:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build angular
        run: |
          cd frontend/angular/crypto
          npm run build
          
