name: Test
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install npm and angular packages
        run: |
          npm install
  build:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build angular
        run: ng build --prod
      - name: Run angular
        run: ng serve
          
